apiVersion: apps/v1
kind: Deployment
metadata:
  name: poitldemo-deployment
  labels:
    app: poitldemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poitldemo
  template:
    metadata:
      labels:
        app: poitldemo
    spec:
      containers:
      - name: poi-tl-demo
        image: /huway0310/poitldemo:0.0.1-SNAPSHOT
        env:
        - name: "PORT"
          value: "8080"