apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordutil
  labels:
    app: wordutil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordutil
  template:
    metadata:
      labels:
        app: wordutil
    spec:
      containers:
      - name: wordutil
        image: huway0310/wordutil:latest
        env:
        - name: "PORT"
          value: "8080"